message-prefix: "&8\u00bb&a "

messages:
  # Shown when players try to use commands that they don't have permission to use
  no-permission: "&cYou need the permission %s to do that!"
  # Shown when players try to start another timer when they already have one going
  already-busy: "&cThat player already has a timer running!"
  # Usage for the admin command (/xtimer)
  usage-admin: "Usage: &7/xtimer reload"
  # Usage for the timer command (/timer)
  usage-timer: "Usage: &7/timer <player> <seconds> <command>"
  # Shown when the config is reloaded
  config-reloaded: "The config has been reloaded!"
  # Shown if no player is online with the given name
  invalid-player: "&cThat is not a valid player!"
  # Shown if an invalid timer duration is given
  invalid-time: "&cInvalid timer duration! You must enter a whole number greater than zero."

