main: com.rayzr522.xtimer.XTimer
name: XTimer
version: 1.0.0
description: Run commands after a certain amount of time and show the timer through the XP bar
author: Rayzr
commands:
  xtimer:
    description: XTimer admin command
    usage: "\u00A7cRayzr dun fracked somethin' up"
  timer:
    description: Starts a new timer
    usage: "\u00A7cRayzr dun fracked somethin' up"